spring:
  devtools:
    restart:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: momodo123!
    username: admin
    url: jdbc:mysql://momodo-rds.cyd4vpveilbg.us-east-1.rds.amazonaws.com:3306/momodo?useSSL=false&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul&rewriteBatchedStatements=true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

jwt:
  header: Authorization
  refresh-token-validity-in-seconds: 86400
  refresh-token-secret: d29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2FkCg==
  access-token-validity-in-seconds: 600
  secret: aGVsbG8gd29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2EK

kakao:
  get:
    user:
      me:
        url: https://kapi.kakao.com/v2/user/me

google:
  secret: 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
  user:
    url: https://www.googleapis.com
  redirect:
    uri: http://localhost:8090/api/v1/app/social-login/google
  auth:
    url: https://oauth2.googleapis.com
    scope: profile,email,openid
  client:
    id: 208803528904-u3k592bn8rmvl7bqdlikp4rsh9ak7b95.apps.googleusercontent.com
  login:
    url: https://accounts.google.com

org:
  hibernate:
    orm:
      jdbc:
        bind: trace

logging:
  level:
    org:
      hibernate:
        SQL: debug
